<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="lala Rest Api Testing" duration-ms="2116" started-at="2018-11-20T10:47:52Z" finished-at="2018-11-20T10:47:54Z">
    <groups>
    </groups>
    <test name="lalaTestNGTest" duration-ms="2116" started-at="2018-11-20T10:47:52Z" finished-at="2018-11-20T10:47:54Z">
      <class name="com.lala.test.CancelOrderTest">
        <test-method status="PASS" signature="suitelalaTestNGTest()[pri:0, instance:com.lala.test.CancelOrderTest@396a51ab]" name="suitelalaTestNGTest" is-config="true" duration-ms="1" started-at="2018-11-20T16:17:52Z" finished-at="2018-11-20T16:17:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- suitelalaTestNGTest -->
        <test-method status="PASS" signature="verifyCancelOrder()[pri:6, instance:com.lala.test.CancelOrderTest@396a51ab]" name="verifyCancelOrder" duration-ms="1681" started-at="2018-11-20T16:17:52Z" finished-at="2018-11-20T16:17:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyCancelOrder -->
      </class> <!-- com.lala.test.CancelOrderTest -->
      <class name="com.lala.test.PlaceOrderTest">
        <test-method status="PASS" signature="suitelalaTestNGTest()[pri:0, instance:com.lala.test.PlaceOrderTest@5034c75a]" name="suitelalaTestNGTest" is-config="true" duration-ms="7" started-at="2018-11-20T16:17:52Z" finished-at="2018-11-20T16:17:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- suitelalaTestNGTest -->
        <test-method status="FAIL" signature="verifyFutureOrder()[pri:1, instance:com.lala.test.PlaceOrderTest@5034c75a]" name="verifyFutureOrder" duration-ms="179" started-at="2018-11-20T16:17:53Z" finished-at="2018-11-20T16:17:54Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test is failed, Error while placing order, please check server connection.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test is failed, Error while placing order, please check server connection.
	at org.testng.Assert.fail(Assert.java:94)
	at com.lala.test.PlaceOrderTest.verifyFutureOrder(PlaceOrderTest.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyFutureOrder -->
        <test-method status="PASS" signature="verifyNewOrder()[pri:1, instance:com.lala.test.PlaceOrderTest@5034c75a]" name="verifyNewOrder" duration-ms="231" started-at="2018-11-20T16:17:54Z" finished-at="2018-11-20T16:17:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyNewOrder -->
      </class> <!-- com.lala.test.PlaceOrderTest -->
    </test> <!-- lalaTestNGTest -->
  </suite> <!-- lala Rest Api Testing -->
</testng-results>
