<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Stock10671.local" name="com.lala.test.RunTest" tests="6" failures="1" timestamp="18 Nov 2018 11:59:37 GMT" time="3.677" errors="0">
  <testcase name="verifyPlaceOrder" time="2.812" classname="com.lala.test.RunTest"/>
  <testcase name="verifyFetchOrderWhenOrderDoesNotExist" time="0.030" classname="com.lala.test.RunTest">
    <failure type="java.lang.AssertionError" message="Test is failed, status code not matched please check you GET request payload">
      <![CDATA[java.lang.AssertionError: Test is failed, status code not matched please check you GET request payload
	at org.testng.Assert.fail(Assert.java:94)
	at com.lala.test.requests.FetchOrder.verifyStatusCode(FetchOrder.java:39)
	at com.lala.test.RunTest.verifyFetchOrderWhenOrderDoesNotExist(RunTest.java:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyFetchOrderWhenOrderDoesNotExist -->
  <testcase name="verifyFetchOrderWhenOrderExist" time="0.221" classname="com.lala.test.RunTest"/>
  <testcase name="verifyCancelOrder" time="0.191" classname="com.lala.test.RunTest"/>
  <testcase name="verifyDriveToTakeOrder" time="0.202" classname="com.lala.test.RunTest"/>
  <testcase name="verifyDriveToComplete" time="0.221" classname="com.lala.test.RunTest"/>
</testsuite> <!-- com.lala.test.RunTest -->
